alg_name: "LoRA"
model_name: "hugging_cache/llama2-7b"
device: 0

layers: [20, 21, 22, 23, 24]
num_steps: 20
batch_size: 1
max_length: 30
lr: 5e-4
weight_decay: 0
kl_factor: 0
norm_constraint: false
rewrite_module_tmp: ["model.layers.{}.self_attn.q_proj.lora.A","model.layers.{}.self_attn.q_proj.lora.B","model.layers.{}.self_attn.v_proj.lora.A","model.layers.{}.self_attn.v_proj.lora.B"]
layer_module_tmp: "model.layers.{}"
mlp_module_tmp: "model.layers.{}.mlp"
attn_module_tmp: "model.layers.{}.self_attn"
ln_f_module: "model.norm"
lm_head_module: "lm_head"

#["model.layers.{}.mlp.down_proj.lora.A","model.layers.{}.mlp.down_proj.lora.B"]
#["model.layers.{}.self_attn.q_proj.lora.A","model.layers.{}.self_attn.q_proj.lora.B","model.layers.{}.self_attn.v_proj.lora.A","model.layers.{}.self_attn.v_proj.lora.B"]