alg_name: "OFT"
model_name: "./hugging_cache/llama2-7b"
#model_name: "./hugging_cache/Meta-Llama-3-8B"
device: 0

layers: [19,20,21]
num_steps: 20
batch_size: 10
max_length: 30
lr: 5e-4
weight_decay: 0
kl_factor: 0
norm_constraint: false
rewrite_module_tmp: "model.layers.{}.mlp.down_proj.R"
layer_module_tmp: "model.layers.{}"
mlp_module_tmp: "model.layers.{}.mlp"
attn_module_tmp: "model.layers.{}.self_attn"
ln_f_module: "model.norm"
lm_head_module: "lm_head"